'use client';
import {customerLink} from '@/domain/customer-care';
import {useState} from 'react';
import {Task,taskSchema} from '@/domain/models';
import {useStore} from '@/services/repository/context';
import {Modal,Field,Empty} from '@/components/ui';
import {Check,Phone,CalendarDays,MessageCircle,Clock3} from 'lucide-react';
const labels={CALL:'Gọi điện',ZALO:'Nhắn Zalo',VIEWING:'Dẫn xem',SEND_PROPERTY:'Gửi BĐS',LEGAL:'Pháp lý',FOLLOW_UP:'Chăm sóc',OTHER:'Khác'};
export function TaskForm({onClose,initial}:{onClose:()=>void;initial?:Task}){const {data,commit,busy}=useStore();const [form,setForm]=useState<Task>(initial||{id:crypto.randomUUID(),title:'',type:'CALL',status:'TODO',priority:'NORMAL'});const [error,setError]=useState('');return <Modal title={initial?'Sửa công việc':'Tạo công việc / lịch hẹn'} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();const r=taskSchema.safeParse(form);if(!r.success){setError(r.error.issues[0].message);return}try{await commit(d=>{d.tasks=d.tasks.filter(t=>t.id!==form.id);d.tasks.unshift(form)},form.customerId||form.id,'Lưu công việc');onClose()}catch(e){setError((e as Error).message)}}}><div className="form-grid"><Field label="Nội dung *" full><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Loại"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value as Task['type']})}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Ưu tiên"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Task['priority']})}><option value="NORMAL">Bình thường</option><option value="HIGH">Cao</option><option value="URGENT">Gấp</option></select></Field><Field label="Ngày giờ" full><input type="datetime-local" value={form.dueAt?new Date(new Date(form.dueAt).getTime()-new Date(form.dueAt).getTimezoneOffset()*60000).toISOString().slice(0,16):''} onChange={e=>setForm({...form,dueAt:e.target.value?new Date(e.target.value).toISOString():undefined})}/></Field><Field label="Khách"><select value={form.customerId||''} onChange={e=>setForm({...form,customerId:e.target.value||undefined})}><option value="">Không liên kết</option>{data.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Bất động sản"><select value={form.propertyId||''} onChange={e=>setForm({...form,propertyId:e.target.value||undefined})}><option value="">Không liên kết</option>{data.properties.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></Field><Field label="Ghi chú" full><textarea value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})}/></Field></div>{error&&<p className="error">{error}</p>}<div className="form-actions"><button className="primary" disabled={busy}>Lưu công việc</button></div></form></Modal>}
export function TaskCard({task:t,onEdit}:{task:Task;onEdit?:()=>void}){const {data,commit,busy}=useStore();const overdue=t.status==='TODO'&&!!t.dueAt&&new Date(t.dueAt).getTime()<Date.now();return <div className={'task-card '+(t.status==='DONE'?'done':'')}><button disabled={busy} className="task-check" aria-label={t.status==='DONE'?'Mở lại công việc':'Hoàn thành công việc'} onClick={()=>commit(d=>{const item=d.tasks.find(x=>x.id===t.id)!;item.status=t.status==='DONE'?'TODO':'DONE';item.completedAt=item.status==='DONE'?new Date().toISOString():undefined},t.customerId||t.id,t.status==='DONE'?'Mở lại công việc':'Hoàn thành công việc').catch(()=>{})}>{t.status==='DONE'&&<Check size={17}/>}</button><div className="task-content"><button className="task-title" onClick={onEdit}>{t.title}</button><div className="task-meta"><span>{labels[t.type]}</span><span className={overdue?'overdue':''}>{t.dueAt?(overdue?'Quá hạn · ':'')+new Date(t.dueAt).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'Chưa hẹn giờ'}</span></div>{t.customerId&&<a href={customerLink(t.customerId)}>Khách: {data.customers.find(c=>c.id===t.customerId)?.name||'Xem hồ sơ'} →</a>}{t.note&&<p className="care-note">{t.note}</p>}{t.completedAt&&<small>Hoàn thành: {new Date(t.completedAt).toLocaleString('vi-VN')}</small>}</div>{t.priority==='URGENT'&&<span className="badge red">Gấp</span>}</div>}
export function sortTasks(items:Task[]){return [...items].sort((a,b)=>{const rank=(t:Task)=>(t.status==='TODO'?0:100)+(t.dueAt&&new Date(t.dueAt).getTime()<Date.now()?0:10)+(t.priority==='URGENT'?0:t.priority==='HIGH'?1:2);return rank(a)-rank(b)||(new Date(a.dueAt||'2099').getTime()-new Date(b.dueAt||'2099').getTime())})}
export default function Tasks({calendar=false}:{calendar?:boolean}){const {data}=useStore();const [edit,setEdit]=useState<Task|true|null>(null);const [filter,setFilter]=useState('TODO');const [date,setDate]=useState('');const items=sortTasks(data.tasks.filter(t=>(!filter||t.status===filter)&&(!calendar||!date||(t.dueAt&&new Date(t.dueAt).toLocaleDateString('sv-SE')===date))));return <><div className="page-heading"><div><p className="eyebrow">MỖI NGÀY, MỘT BƯỚC TIẾN</p><h1>{calendar?'Lịch hẹn':'Công việc'}</h1></div><button className="primary" onClick={()=>setEdit(true)}>+ {calendar?'Tạo lịch hẹn':'Tạo công việc'}</button></div><div className="toolbar"><div className="chips">{[['TODO','Cần làm'],['DONE','Hoàn thành'],['','Tất cả']].map(([k,v])=><button key={k} className={'chip '+(filter===k?'active':'')} onClick={()=>setFilter(k)}>{v}</button>)}</div>{calendar&&<input aria-label="Ngày hẹn" type="date" value={date} onChange={e=>setDate(e.target.value)}/>}</div><div className="panel">{items.length?items.map(t=><TaskCard key={t.id} task={t} onEdit={()=>setEdit(t)}/>):<Empty title="Không có công việc trong mục này" action="Tạo công việc" onAction={()=>setEdit(true)}/>}</div>{edit&&<TaskForm initial={edit===true?undefined:edit} onClose={()=>setEdit(null)}/>}</>}

