'use client';
import {useEffect,useState} from 'react';
import {Field} from '@/components/ui';
import {readAIConfig,saveAIConfig} from '@/services/ai/client';
const names:Record<string,string>={openai:'OpenAI GPT',groq:'Groq',gemini:'Gemini'};
export default function AISettings(){const [provider,setProvider]=useState('openai');const [key,setKey]=useState('');const [model,setModel]=useState('');const [config,setConfig]=useState<any>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [models,setModels]=useState<string[]>([]);
 useEffect(()=>{readAIConfig().then(c=>{setConfig(c);setProvider(c.active);setModel(c.providers[c.active].model)}).catch(e=>setMessage(e.message))},[]);
 async function save(remove=false,test=false){setBusy(true);setMessage('');try{const result=await saveAIConfig({provider,model,key,remove,test});setConfig(result);setModel(result.providers[provider].model);setKey('');setMessage(remove?'Đã xóa key đã nhập.':(result.tested?'Kết nối thành công. ':'Đã lưu. ')+'AI Copilot sẽ dùng '+names[provider]+' / '+result.providers[provider].model+'.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel settings-panel"><h2>API key GPT / Groq / Gemini</h2><p>Chọn nhà cung cấp AI và nhập key của bạn.</p><Field label="Nhà cung cấp"><select value={provider} onChange={e=>{const p=e.target.value;setProvider(p);setModel(config?.providers[p]?.model||'');setKey('');setModels([]);setMessage('')}}>{Object.entries(names).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Tên model"><input list="ai-provider-models" value={model} placeholder={provider==="groq"?"Để trống: tự chọn model Groq":"Tên model được hỗ trợ trong tài khoản API"} onChange={e=>setModel(e.target.value)} autoComplete="off"/><datalist id="ai-provider-models">{models.map(id=><option key={id} value={id}/>)}</datalist></Field><Field label="API key"><input type="password" value={key} onChange={e=>setKey(e.target.value)} autoComplete="new-password" spellCheck={false} placeholder={config?.providers[provider]?.configured?'Đã nhập key · để trống để giữ nguyên':'Dán API key tại đây'}/></Field><p className="muted">Key được giữ tạm ở máy chủ trong phiên 24 giờ, không đưa vào dữ liệu CRM hoặc file sao lưu. Khi máy chủ khởi động lại, bạn cần nhập lại key.</p><div className="action-row">{provider==="groq"&&<button disabled={busy} className="secondary" onClick={async()=>{setBusy(true);setMessage("");try{const r=await saveAIConfig({provider,key,model,listModels:true});setModels(r.models);setModel(r.suggested);setMessage("Đã lấy "+r.models.length+" model từ Groq. Bấm Lưu và kiểm tra để xác nhận.")}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>Lấy model từ Groq</button>}<button disabled={busy} className="primary" onClick={()=>save(false,true)}>{busy?'Đang lưu…':'Lưu và kiểm tra'}</button>{config?.providers[provider]?.configured&&<button disabled={busy} className="secondary" onClick={()=>save(true)}>Xóa key đã nhập</button>}</div>{message&&<p role="status">{message}</p>}<p className="muted">Model phải hỗ trợ JSON; chọn model hỗ trợ ảnh nếu dùng screenshot. Có thể dùng key tại đây mà chưa cần kết nối Firebase.</p></section>
}

