import {Property,Requirement} from './models';
import {defaultSettings} from '@/config';
const norm=(s?:string)=>s?.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d').trim()||'';
export function normalizeProperty(p:Property):Property {const area=p.dimensions.width*p.dimensions.length;return {...p,title:p.title.trim(),bedrooms:['LAND','AGRICULTURAL_LAND'].includes(p.type)?0:p.bedrooms,dimensions:{...p.dimensions,calculatedArea:area},price:{...p.price,pricePerM2:area?p.price.amount/area:0},owner:{...p.owner,name:p.owner.name.trim(),phone:p.owner.phone?.replace(/\s/g,'')}};}
export function duplicateCandidates(p:Property,items:Property[]) {return items.filter(x=>x.id!==p.id).map(x=>{let score=0;const reasons:string[]=[];const add=(ok:boolean,n:number,why:string)=>{if(ok){score+=n;reasons.push(why)}};add(!!p.owner.phone&&p.owner.phone.replace(/\D/g,'')===x.owner.phone?.replace(/\D/g,''),25,'Cùng SĐT chủ');add(norm(p.owner.name)===norm(x.owner.name),15,'Cùng tên chủ');add(norm(p.location.wardCommune)===norm(x.location.wardCommune),15,'Cùng khu vực');add(p.type===x.type,5,'Cùng loại');add(Math.abs(p.dimensions.width-x.dimensions.width)<0.3,10,'Ngang tương tự');add(Math.abs(p.dimensions.length-x.dimensions.length)<1,10,'Dài tương tự');add(Math.abs(p.price.amount-x.price.amount)/Math.max(p.price.amount,1)<0.05,10,'Giá tương tự');add(norm(p.title)===norm(x.title),10,'Cùng tiêu đề');return {property:x,score,reasons}}).filter(x=>x.score>=65).sort((a,b)=>b.score-a.score);}
export function matchProperty(p:Property,r:Requirement,weights:Record<string,number>=defaultSettings.weights){
 const area=p.dimensions.calculatedArea||p.dimensions.width*p.dimensions.length;
 const failures:string[]=[];const check=(bad:boolean,msg:string)=>{if(bad)failures.push(msg)};
 check(p.status!=='ACTIVE'||r.status!=='ACTIVE','Không hoạt động');check(!!r.transactionType&&r.transactionType!==p.transactionType,'Hình thức');check(!!r.propertyTypes?.length&&!r.propertyTypes.includes(p.type),'Loại BĐS');check(!!r.provinceCities?.length&&!r.provinceCities.includes(p.location.provinceCity),'Tỉnh/thành');check(!!r.wardCommunes?.length&&!r.wardCommunes.includes(p.location.wardCommune),'Khu vực');check(r.priceMax!==undefined&&p.price.amount>r.priceMax,'Vượt ngân sách');check(r.priceMin!==undefined&&p.price.amount<r.priceMin,'Dưới ngân sách');check(r.widthMin!==undefined&&p.dimensions.width<r.widthMin,'Ngang');check(r.lengthMin!==undefined&&p.dimensions.length<r.lengthMin,'Dài');check(r.areaMin!==undefined&&area<r.areaMin,'Diện tích nhỏ');check(r.areaMax!==undefined&&area>r.areaMax,'Diện tích lớn');check(r.bedroomsMin!==undefined&&p.bedrooms<r.bedroomsMin,'Thiếu phòng ngủ');check(!!r.directions?.length&&!r.directions.includes(p.direction),'Hướng');check(r.carAccess===true&&p.road?.carAccess!==true,'Chưa có ô tô tới');check(!!r.legalPreferences?.some(x=>!norm(p.legal?.note).includes(norm(x))),'Chưa đủ pháp lý');
 if(failures.length)return {eligible:false,score:0,reasons:failures};
 const signals:[string,boolean,string][]=[['area',!!r.wardCommunes?.length,'Đúng khu vực'],['price',r.priceMax!==undefined||r.priceMin!==undefined,'Trong ngân sách'],['type',!!r.propertyTypes?.length,'Đúng loại BĐS'],['dimensions',r.areaMin!==undefined||r.widthMin!==undefined||r.lengthMin!==undefined||r.areaMax!==undefined,'Đủ diện tích / kích thước'],['bedrooms',r.bedroomsMin!==undefined,'Đủ phòng ngủ'],['direction',!!r.directions?.length,'Đúng hướng'],['legal',!!r.legalPreferences?.length,'Pháp lý phù hợp'],['car',r.carAccess===true,'Ô tô tới']];
 let total=0,points=0;const reasons:string[]=[];for(const [k,active,reason]of signals){if(active){total+=weights[k]||0;points+=weights[k]||0;reasons.push(reason)}}
 if(r.semanticPreferences?.length){total+=weights.semantic||0;const matched=r.semanticPreferences.filter(s=>norm((p.details||'')+' '+p.note+' '+p.title).includes(norm(s))).length;points+=(weights.semantic||0)*matched/r.semanticPreferences.length;if(matched)reasons.push('Có từ khóa sở thích')}
 return {eligible:true,score:total?Math.round(points/total*100):0,reasons:reasons.length?reasons:['Chưa có tiêu chí cụ thể để chấm điểm']};
}
export function freshness(p:Property){return Math.max(0,Math.floor((Date.now()-new Date(p.lastVerifiedAt||p.updatedAt).getTime())/86400000))}
export function searchProperties(items:Property[],q:string){const s=norm(q);return items.filter(p=>norm([p.title,p.code,p.location.wardCommune,p.owner.name,p.owner.phone,p.note,p.details].join(' ')).includes(s));}

