import assert from 'node:assert/strict';import test from 'node:test';import {demoDatabase} from '../src/services/repository/demo';import {createBackup,parseBackup,externalImageCount} from '../src/domain/backup';import {matchCustomerProperties} from '../src/domain/customer-matching';import {recordCare,pendingCustomers} from '../src/domain/customer-care';import {billionsToVnd} from '../src/domain/property-price';import {generateJSON} from '../src/services/ai/provider';
test('Backup roundtrip keeps properties, images, customers and follow-up data',()=>{const d=demoDatabase();d.properties[0].media.images[0].url='data:image/png;base64,aGVsbG8=';recordCare(d,{customerId:d.customers[0].id,type:'CALL',note:'Hẹn xem',nextAt:'2030-01-02'},'2030-01-01');assert.deepEqual(parseBackup(createBackup(d)),JSON.parse(JSON.stringify(d)));assert.equal(parseBackup(createBackup(d)).tasks[0].type,'FOLLOW_UP')});
test('Old web V1 backup imports without migration or mutation',()=>{const d=demoDatabase();const before=JSON.stringify(d);assert.deepEqual(parseBackup(JSON.stringify({schemaVersion:1,data:d})),d);assert.equal(JSON.stringify(d),before)});
test('Malformed backups and duplicate IDs fail before restore',()=>{const d=demoDatabase();assert.throws(()=>parseBackup('{'));assert.throws(()=>parseBackup(JSON.stringify({schemaVersion:2,data:d})));d.customers.push(d.customers[0]);assert.throws(()=>parseBackup(createBackup(d)))});
test('Missing relationship and invalid weights are rejected',()=>{const d=demoDatabase();d.requirements[0].customerId='missing';assert.throws(()=>parseBackup(createBackup(d)));const other=demoDatabase();other.settings.weights.price=-1;assert.throws(()=>parseBackup(createBackup(other)))});
test('API secrets outside CRM schema are never exported',()=>{const d=demoDatabase();(d as any).apiKey='PRIVATE KEY';assert.ok(!createBackup(d).includes('PRIVATE KEY'))});
test('Local matching and pending care work after restoring',()=>{const d=parseBackup(createBackup(demoDatabase()));const matches=matchCustomerProperties(d.customers[0].id,d.requirements,d.properties,d.settings.weights);assert.ok(matches.every(m=>m.score>=70));assert.ok(pendingCustomers(d).length>0)});
test('Vietnamese price remains exact VND',()=>{assert.equal(billionsToVnd('1,5'),1500000000)});
test('Native AI adapter keeps JSON format and uses safe model errors',async()=>{const response=await generateJSON({provider:'groq',model:'test',key:'native'},'JSON',{text:'house'},(async()=>new Response(JSON.stringify({choices:[{message:{content:'{"title":"Nhà"}'}}]}),{status:200})) as typeof fetch);assert.equal(response.title,'Nhà');await assert.rejects(()=>generateJSON({provider:'groq',model:'test',key:'native'},'JSON',{},(async()=>new Response('secret error',{status:401})) as typeof fetch),/API key/)});
