'use client';
import {isRecommendedMatch} from '@/domain/match-recommendation';

import {useState} from 'react';
import {useStore} from '@/services/repository/context';
import {matchProperty} from '@/domain/engines';
import {money} from '@/config';
import {Empty} from '@/components/ui';
import {ArrowLeftRight,Sparkles} from 'lucide-react';
import {PropertyDetail} from '@/modules/properties';
import {PropertyForm} from '@/modules/properties/form';
export default function Matching(){const {data}=useStore();const [reverse,setReverse]=useState(false);const [id,setId]=useState('');const [detail,setDetail]=useState<string|null>(null);const [edit,setEdit]=useState<any>(null);const results=data.requirements.flatMap(r=>data.properties.map(p=>({r,p,...matchProperty(p,r,data.settings.weights)}))).filter(x=>isRecommendedMatch(x)&&(!id||(reverse?x.p.id===id:x.r.customerId===id))).sort((a,b)=>b.score-a.score);const selected=data.properties.find(p=>p.id===detail);return <><div className="page-heading"><div><p className="eyebrow">ĐÚNG NHU CẦU · ĐÚNG CƠ HỘI</p><h1>Matching hai chiều</h1></div><span className="badge green"><Sparkles size={15}/>Điều kiện + trọng số</span></div><div className="matching-hero"><div className="chips"><button className={'chip '+(!reverse?'active':'')} onClick={()=>{setReverse(false);setId('')}}>Khách → Bất động sản</button><button className={'chip '+(reverse?'active':'')} onClick={()=>{setReverse(true);setId('')}}>Bất động sản → Khách</button></div><select aria-label="Chọn đối tượng matching" value={id} onChange={e=>setId(e.target.value)}><option value="">{reverse?'Tất cả bất động sản':'Tất cả khách hàng'}</option>{(reverse?data.properties:data.customers).map(x=><option key={x.id} value={x.id}>{'title'in x?x.title:x.name}</option>)}</select><p>Chỉ đề xuất sản phẩm đạt từ 70% và đáp ứng mọi điều kiện bắt buộc. Điểm phản ánh tiêu chí đã cung cấp, không phải xác suất giao dịch.</p></div><div className="section-heading"><h2>{results.length} kết quả phù hợp</h2></div>{results.length?<div className="match-grid">{results.map(x=><article className="panel match-result" key={x.p.id+x.r.id}><div className="match-result-head"><span className="eyebrow">{data.customers.find(c=>c.id===x.r.customerId)?.name}</span><b className="match-badge">{x.score}%</b></div><h3>{x.p.title}</h3><p className="match-price">{money(x.p.price.amount)}</p><p>{x.p.location.wardCommune}</p><div className="reasons">{x.reasons.map(r=><span key={r}>✓ {r}</span>)}</div><button className="text-button" onClick={()=>setDetail(x.p.id)}>Xem bất động sản →</button></article>)}</div>:<Empty title="Chưa tìm thấy cặp phù hợp" description="Thêm khách, nhu cầu và BĐS, hoặc kiểm tra lại các điều kiện bắt buộc."/>}{selected&&<PropertyDetail property={selected} onClose={()=>setDetail(null)} onEdit={()=>{setEdit(selected);setDetail(null)}}/>}{edit&&<PropertyForm initial={edit} onClose={()=>setEdit(null)}/>}</>}

