import {takePropertyPhoto} from '@/native/camera';
'use client';
import {useState} from 'react';
import {Property} from '@/domain/models';
import {propertySchema} from '@/domain/models';
import {normalizeProperty,duplicateCandidates} from '@/domain/engines';
import {directions,propertyTypes,transactions,statuses,certificateStatuses} from '@/config';
import {useStore} from '@/services/repository/context';
import {mediaStorage} from '@/services/media';
import {PriceInput} from '@/components/forms/PriceInput';
import {Modal,Field} from '@/components/ui';
export function PropertyForm({initial,onClose}:{initial?:Record<string,any>;onClose:()=>void}){
 const {data,commit,busy}=useStore();const now=new Date().toISOString();
 const [value,setValue]=useState<any>({id:crypto.randomUUID(),code:'BĐS-'+Date.now().toString().slice(-6),title:'',type:'HOUSE',transactionType:'SALE',status:'ACTIVE',location:{provinceCity:'TP Cần Thơ',wardCommune:''},dimensions:{width:'',length:''},direction:'',bedrooms:'',price:{amount:'',unit:'VND'},owner:{name:'',phone:''},media:{images:[]},createdAt:now,updatedAt:now,...initial});
 const [errors,setErrors]=useState<string[]>([]);const [duplicates,setDuplicates]=useState<ReturnType<typeof duplicateCandidates>>([]);const [pending,setPending]=useState<Property|null>(null);const [uploading,setUploading]=useState(false);const [confirm,setConfirm]=useState(false);
 function set(path:string,v:any){setValue((old:any)=>{const next=structuredClone(old);const keys=path.split('.');let obj=next;for(const key of keys.slice(0,-1)){obj[key]??={};obj=obj[key]}obj[keys.at(-1)!]=v;return next})}
 async function persist(p:Property){await commit(d=>{const i=d.properties.findIndex(x=>x.id===p.id);if(i>=0)d.properties[i]=p;else d.properties.unshift(p);d.drafts=d.drafts.filter(x=>x.id!==p.id)},p.id,initial?'Cập nhật BĐS':'Tạo BĐS');onClose()}
 async function save(){setErrors([]);const raw={...value,bedrooms:['LAND','AGRICULTURAL_LAND'].includes(value.type)?0:value.bedrooms,updatedAt:new Date().toISOString()};const result=propertySchema.safeParse(raw);if(!result.success){setErrors(result.error.issues.map(x=>{const labels:Record<string,string>={title:'Tiêu đề',type:'Loại BĐS',transactionType:'Giao dịch',status:'Trạng thái','location.provinceCity':'Tỉnh / Thành','location.wardCommune':'Phường / Xã','dimensions.width':'Ngang','dimensions.length':'Dài',direction:'Hướng',bedrooms:'Phòng ngủ','price.amount':'Giá','owner.name':'Chủ sở hữu','media.images':'Ảnh',soldInfo:'Thông tin đã bán'};return (labels[x.path.join('.')]||'Thông tin')+': '+(x.code==='invalid_type'?'Vui lòng nhập đúng định dạng.':x.message)}));return}const p=normalizeProperty(result.data);setPending(p);const dup=duplicateCandidates(p,data.properties);if(dup.length){setDuplicates(dup);return}if(initial&&(initial.price?.amount!==p.price.amount||initial.status!==p.status||initial.owner?.name!==p.owner.name)){setConfirm(true);return}await persist(p)}
 async function images(files:FileList|File[]|null){if(!files)return;setUploading(true);try{const results:Awaited<ReturnType<typeof mediaStorage.upload>>[]=[];for(const file of Array.from(files))results.push(await mediaStorage.upload(file));setValue((old:any)=>({...old,media:{...old.media,images:[...old.media.images,...results].map((x,i)=>({...x,order:i}))}}))}catch(e){setErrors([(e as Error).message])}finally{setUploading(false)}}
 const text=(path:string,label:string,type='text',full=false)=>{const v=path.split('.').reduce((o,k)=>o?.[k],value)??'';return <Field label={label} full={full}><input type={type} value={v} min={type==='number'&&!path.includes('latitude')&&!path.includes('longitude')?0:undefined} step={type==='number'?'any':undefined} inputMode={type==='number'?'decimal':undefined} onChange={e=>set(path,type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)}/></Field>};
 return <Modal title={initial?'Chỉnh sửa bất động sản':'Thêm bất động sản'} onClose={onClose} wide><form onSubmit={e=>{e.preventDefault();save().catch(e=>setErrors([e.message]))}}><p className="muted">Thông tin có dấu * cần có để lưu chính thức. Bạn có thể lưu nháp bất cứ lúc nào.</p><div className="form-grid">
 {text('title','Tiêu đề *','text',true)}<Field label="Loại BĐS *"><select value={value.type} onChange={e=>{set('type',e.target.value);if(['LAND','AGRICULTURAL_LAND','WAREHOUSE'].includes(e.target.value))set('bedrooms',0)}}>{Object.entries(propertyTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Giao dịch *"><select value={value.transactionType} onChange={e=>set('transactionType',e.target.value)}>{Object.entries(transactions).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field>
 {text('location.provinceCity','Tỉnh / Thành *')}<Field label="Phường / Xã *"><input list="areas" value={value.location.wardCommune||''} onChange={e=>set('location.wardCommune',e.target.value)}/><datalist id="areas">{data.settings.favoriteAreas.map(x=><option key={x}>{x}</option>)}</datalist></Field><div className="chips span-2">{data.settings.favoriteAreas.map(x=><button key={x} type="button" className={value.location.wardCommune===x?'chip active':'chip'} onClick={()=>set('location.wardCommune',x)}>☆ {x.replace(/Phường |Xã /g,'')}</button>)}</div>
 {text('dimensions.width','Ngang (m) *','number')}{text('dimensions.length','Dài (m) *','number')}<div className="calculated span-2">Diện tích dự kiến <strong>{(Number(value.dimensions.width)*Number(value.dimensions.length)).toLocaleString('vi-VN')} m²</strong></div>
 <Field label="Hướng *" full><div className="direction-grid">{Object.entries(directions).map(([k,v])=><button type="button" className={value.direction===k?'chip active':'chip'} key={k} onClick={()=>set('direction',k)}>{v}</button>)}</div></Field>
 {!['LAND','AGRICULTURAL_LAND'].includes(value.type)&&text('bedrooms','Phòng ngủ *','number')}<PriceInput amount={value.price.amount} onChange={amount=>set('price.amount',amount)}/>{text('owner.name','Chủ sở hữu *')}{text('owner.phone','SĐT chủ','tel')}
 <Field label="Ảnh bất động sản *" full><button type="button" className="secondary" disabled={uploading} onClick={()=>takePropertyPhoto().then(f=>images([f])).catch(e=>setErrors([e.message]))}>Chụp ảnh BĐS</button><input type="file" accept="image/*" multiple onChange={e=>images(e.target.files)}/><div className="media-preview">{value.media.images.map((im:any,i:number)=><div key={im.id}><img src={im.url} alt={'Ảnh '+(i+1)}/><button type="button" onClick={()=>set('media.images',value.media.images.filter((_:any,n:number)=>n!==i))}>Bỏ ảnh</button></div>)}</div>{uploading&&<span>Đang tải ảnh…</span>}</Field>
 {text('location.addressText','Địa chỉ','text',true)}<Field label="Pháp lý" full><select value={value.legal?.certificateStatus||""} onChange={e=>set("legal.certificateStatus",e.target.value||undefined)}><option value="">Chưa rõ / chưa cung cấp</option>{Object.entries(certificateStatuses).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field>{text('legal.note','Ghi chú pháp lý','text',true)}{text('sourceUrl','Link nguồn tin','url',true)}<label className="check span-2"><input type="checkbox" checked={value.road?.carAccess===true} onChange={e=>set('road.carAccess',e.target.checked)}/>Ô tô tới (đã xác minh)</label>{text('media.videoUrl','Link video','url')}{text('location.mapUrl','Link Google Maps','url')}{text('location.latitude','Vĩ độ','number')}{text('location.longitude','Kinh độ','number')}
 <Field label="Thông tin chi tiết" full><textarea rows={6} placeholder="Mô tả kết cấu, hiện trạng, tiện ích, đường vào và các đặc điểm của bất động sản…" value={value.details||""} onChange={e=>set("details",e.target.value)}/></Field><Field label="Ghi chú" full><textarea value={value.note||''} onChange={e=>set('note',e.target.value)}/></Field><Field label="Trạng thái *"><select value={value.status||''} onChange={e=>set('status',e.target.value)}><option value="">Chưa rõ</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field>
 {value.status==='SOLD'&&<><div className="span-2 notice">Giữ nguyên giá đăng. Nhập riêng thông tin giao dịch đã bán.</div>{text('soldInfo.soldAt','Ngày bán *','date')}<PriceInput label="Giá bán thực tế (tỷ đồng) *" amount={value.soldInfo?.actualSoldPrice??''} onChange={amount=>set('soldInfo.actualSoldPrice',amount)}/>{text('soldInfo.note','Ghi chú giao dịch','text',true)}</>}
 </div>{errors.length>0&&<div role="alert" className="error">{errors.map((e,i)=><div key={i}>{e}</div>)}</div>}
 {duplicates.length>0&&<div className="notice"><h3>Có sản phẩm nghi trùng</h3>{duplicates.map(x=><p key={x.property.id}><strong>{x.property.code} · {x.property.title} — {x.score}%</strong><br/>{x.reasons.join(' · ')}</p>)}<p>Kiểm tra thông tin cũ trước khi quyết định lưu thêm.</p><button type="button" className="secondary" disabled={busy} onClick={()=>pending&&persist(pending).catch(e=>setErrors([e.message]))}>Tôi đã kiểm tra, vẫn lưu riêng</button><button type="button" className="text-button" onClick={()=>{setDuplicates([]);setPending(null)}}>Quay lại chỉnh sửa</button></div>}
 {confirm&&<div className="notice"><strong>Xác nhận thay đổi giá, trạng thái hoặc chủ sở hữu?</strong><p>Thay đổi sẽ được ghi vào lịch sử hoạt động.</p><button type="button" disabled={busy} className="primary" onClick={()=>pending&&persist(pending).catch(e=>setErrors([e.message]))}>Xác nhận và lưu</button></div>}
 <div className="form-actions sticky"><button type="button" className="secondary" disabled={busy||uploading} onClick={()=>commit(d=>{d.drafts=d.drafts.filter(x=>x.id!==value.id);d.drafts.unshift(value)},value.id,'Lưu nháp BĐS').then(onClose).catch(e=>setErrors([e.message]))}>Lưu nháp</button><button className="primary" disabled={busy||uploading}>{busy?'Đang lưu…':'Lưu chính thức'}</button></div></form></Modal>
}





