import {collection,getDocs,query,where,limit,doc,writeBatch,orderBy,startAfter,QueryDocumentSnapshot,DocumentData} from 'firebase/firestore';
import {db} from '@/services/firebase/client';
import {Database} from '@/domain/models';
import {emptyDatabase} from './demo';
const names=['properties','drafts','customers','requirements','tasks','activities'] as const;
const key='lam-crm-local-v1';
export function loadLocal():Database {const raw=localStorage.getItem(key);return raw?JSON.parse(raw):emptyDatabase()}
export function saveLocal(data:Database){localStorage.setItem(key,JSON.stringify(data))}
export async function loadCloud(uid:string):Promise<Database>{if(!db)throw Error('Chưa cấu hình Firebase');const result=emptyDatabase();await Promise.all(names.map(async name=>{const snap=await getDocs(query(collection(db!,name),where('userId','==',uid),orderBy('updatedAt','desc'),limit(100)));(result[name] as unknown[])=snap.docs.map(d=>{const {userId,...value}=d.data();return value})}));const settings=await getDocs(query(collection(db,'settings'),where('userId','==',uid),limit(1)));if(settings.docs[0])result.settings=settings.docs[0].data().value;return result;}
export async function loadPropertyPage(uid:string,filters:{type?:string;status?:string;ward?:string},cursor?:QueryDocumentSnapshot<DocumentData>){if(!db)throw Error('Chưa kết nối');const constraints=[where('userId','==',uid)];if(filters.type)constraints.push(where('type','==',filters.type));if(filters.status)constraints.push(where('status','==',filters.status));if(filters.ward)constraints.push(where('location.wardCommune','==',filters.ward));const snap=await getDocs(query(collection(db,'properties'),...constraints,orderBy('updatedAt','desc'),...(cursor?[startAfter(cursor)]:[]),limit(30)));return {items:snap.docs.map(d=>d.data()),cursor:snap.docs.at(-1),hasMore:snap.size===30}}
const clean=(v:unknown)=>JSON.parse(JSON.stringify(v));
export async function saveCloud(uid:string,previous:Database,next:Database){if(!db)throw Error('Chưa kết nối');if(JSON.stringify([...next.properties,...next.drafts]).includes('data:image/'))throw Error('Ảnh cần được tải lên Storage, không lưu trực tiếp trong Firestore.');const batch=writeBatch(db);let count=0;for(const name of names){const prev=new Map((previous[name] as {id:string}[]).map(x=>[x.id,x]));for(const item of next[name] as {id:string}[]){if(JSON.stringify(item)!==JSON.stringify(prev.get(item.id))){batch.set(doc(db,name,`${uid}_${item.id}`),clean({...item,userId:uid,updatedAt:new Date().toISOString()}));count++}prev.delete(item.id)}for(const id of prev.keys()){batch.delete(doc(db,name,`${uid}_${id}`));count++}}if(JSON.stringify(previous.settings)!==JSON.stringify(next.settings)){batch.set(doc(db,'settings',uid),{userId:uid,value:clean(next.settings)});count++}if(count>450)throw Error('Thay đổi quá lớn. Vui lòng chia nhỏ dữ liệu.');if(count)await batch.commit()}


// Bulk reads are reserved for explicit backups; normal views read bounded pages.
export async function exportCloud(uid:string):Promise<Database>{if(!db)throw Error('Chưa kết nối');const result=emptyDatabase();for(const name of names){let cursor:QueryDocumentSnapshot<DocumentData>|undefined;let done=false;while(!done){const snap=await getDocs(query(collection(db,name),where('userId','==',uid),orderBy('updatedAt','desc'),...(cursor?[startAfter(cursor)]:[]),limit(100)));(result[name] as unknown[]).push(...snap.docs.map(d=>{const {userId,...value}=d.data();return value}));cursor=snap.docs.at(-1);done=snap.size<100}}const settings=await getDocs(query(collection(db,'settings'),where('userId','==',uid),limit(1)));if(settings.docs[0])result.settings=settings.docs[0].data().value;return result;}
