import { initializeApp, getApps } from 'firebase/app';
import {getAuth,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged,User} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';
import {getStorage} from 'firebase/storage';
export const firebaseConfigured=!!process.env.NEXT_PUBLIC_FIREBASE_API_KEY && !!process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
const config={apiKey:process.env.NEXT_PUBLIC_FIREBASE_API_KEY,authDomain:process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,projectId:process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,storageBucket:process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,appId:process.env.NEXT_PUBLIC_FIREBASE_APP_ID};
const app=firebaseConfigured?(getApps()[0]||initializeApp(config)):null;
export const auth=app?getAuth(app):null;
export const db=app?getFirestore(app):null;
export const storage=app?getStorage(app):null;
export const login=()=>{if(!auth)throw Error('Chưa cấu hình Firebase. Xem hướng dẫn cài đặt.');return signInWithPopup(auth,new GoogleAuthProvider())};
export const logout=()=>auth?signOut(auth):Promise.resolve();
export const watchAuth=(fn:(u:User|null)=>void)=>auth?onAuthStateChanged(auth,fn):()=>{};
