'use client';
import {useState} from 'react';
import {Customer,Task} from '@/domain/models';
import {contactLinks,customerLink,pendingCustomers,recordCare} from '@/domain/customer-care';
import {useStore} from '@/services/repository/context';
export function ContactActions({customer,open=false}:{customer:Customer;open?:boolean}){
 const links=contactLinks(customer);
 return <div className="action-row">{open&&<a className="secondary" href={customerLink(customer.id)} onClick={()=>{if(location.hash===customerLink(customer.id))window.dispatchEvent(new HashChangeEvent('hashchange'))}}>Hồ sơ khách →</a>}{links.phone&&<a className="secondary" href={links.phone}>Gọi khách</a>}{links.zalo&&<a className="secondary" href={links.zalo} target="_blank" rel="noreferrer">Zalo</a>}</div>;
}
export function CustomerCare({customer,propertyId}:{customer:Customer;propertyId?:string}){
 const {data,commit,busy}=useStore();
 const [note,setNote]=useState('');const [type,setType]=useState<Task['type']>('CALL');const [nextAt,setNextAt]=useState('');const [completeTaskId,setCompleteTaskId]=useState('');const [error,setError]=useState('');
 const tasks=data.tasks.filter(t=>t.customerId===customer.id);
 return <section className="care-panel"><h3>Chăm sóc · {customer.name}</h3><ContactActions customer={customer}/><p className="muted">Sau khi liên hệ, ghi kết quả và hẹn lần tiếp theo. Mở cuộc gọi / Zalo chưa được tính là đã chăm sóc.</p><form onSubmit={async e=>{e.preventDefault();setError('');try{await commit(d=>recordCare(d,{customerId:customer.id,propertyId,type,note,nextAt:nextAt?new Date(nextAt).toISOString():undefined,completeTaskId:completeTaskId||undefined}),customer.id,'Ghi nhận chăm sóc: '+note.trim()+(nextAt?' · Đã hẹn chăm sóc tiếp':''));setNote('');setNextAt('');setCompleteTaskId('')}catch(e){setError((e as Error).message)}}}><div className="form-grid"><label>Hình thức<select value={type} onChange={e=>setType(e.target.value as Task['type'])}><option value="CALL">Gọi điện</option><option value="ZALO">Zalo</option><option value="VIEWING">Dẫn xem BĐS</option><option value="SEND_PROPERTY">Gửi sản phẩm</option><option value="FOLLOW_UP">Chăm sóc khác</option></select></label><label>Hoàn thành việc đang chờ (tùy chọn)<select value={completeTaskId} onChange={e=>setCompleteTaskId(e.target.value)}><option value="">Ghi nhận lần chăm sóc mới</option>{tasks.filter(t=>t.status==='TODO'&&(!propertyId||!t.propertyId||t.propertyId===propertyId)).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label className="span-2">Kết quả / ghi chú quá trình chăm sóc *<textarea required rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Khách phản hồi thế nào, cần gửi thêm gì…"/></label><label className="span-2">Hẹn chăm sóc tiếp (tùy chọn)<input type="datetime-local" value={nextAt} onChange={e=>setNextAt(e.target.value)}/></label></div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>Lưu chăm sóc{nextAt?' & tạo việc follow-up':''}</button></form><h4>Việc đang chờ · {tasks.filter(t=>t.status==='TODO').length}</h4>{tasks.filter(t=>t.status==='TODO').map(t=><p className="timeline" key={t.id}>{t.title}<small>{t.dueAt?new Date(t.dueAt).toLocaleString('vi-VN'):'Chưa hẹn giờ'}</small>{t.note&&<span className="care-note">{t.note}</span>}</p>)}<h4>Lịch sử kết quả</h4>{tasks.filter(t=>t.status==='DONE').sort((a,b)=>(b.completedAt||'').localeCompare(a.completedAt||'')).map(t=><div className="timeline" key={t.id}><strong>{t.title}</strong><small>{t.completedAt?new Date(t.completedAt).toLocaleString('vi-VN'):'Đã hoàn thành'}</small>{t.propertyId&&<small>BĐS: {data.properties.find(p=>p.id===t.propertyId)?.title||'Đã gỡ'}</small>}<p className="care-note">{t.note||'Chưa có ghi chú kết quả'}</p></div>)}</section>;
}
export function PendingCare(){const {data}=useStore();const items=pendingCustomers(data);return <section className="panel care-panel"><h2>Khách đang tìm / chờ chăm sóc · {items.length}</h2><p className="muted">Ưu tiên lịch quá hạn và khách chưa có việc hẹn. Khách tạm dừng hoặc đã giao dịch được ẩn.</p>{items.length?items.map(({customer,tasks,due,overdue,searching})=><div className="care-pending-row" key={customer.id}><div><a className="card-title" href={customerLink(customer.id)}>{customer.name}</a><p className={overdue?'overdue':'muted'}>{searching?'Đang tìm · ':''}{overdue?'Đến hạn / quá hạn · ':''}{due?new Date(due.dueAt!).toLocaleString('vi-VN'):tasks.length?'Chưa hẹn giờ chăm sóc':'Chưa có lịch chăm sóc'} · {tasks.length} việc chờ</p></div><ContactActions customer={customer} open/></div>):<p className="muted">Chưa có khách đang chờ chăm sóc.</p>}</section>}
